---
title: "Biglasso on CA-CF datamart"
output: html_notebook
---
```{r global_options, include=FALSE}
knitr::opts_chunk$set(fig.width=12, fig.height=8, fig.path='Figs/', warning=FALSE, message=FALSE)
```

```{r, message=FALSE}
require(biglasso)
require(bigtabulate)
```

```{r, echo=FALSE}
plot.lift.nice <- function(probas, target, subtitle = "Modèle", positive = 1)
{
  require(ggplot2)
  require(ROCR)

  pred <- prediction(probas, target)
  perf <- performance(pred, "tpr", "fpr")
  auc <- performance(pred, "auc")@y.values[[1]]
  target_rate <- length(target[target == positive]) / length(target)
  
  x <- perf@x.values[[1]]
  y <- perf@y.values[[1]]
  
  perfect_model <-
    data.frame(x = c(0, target_rate, 1), y = c(0, 1, 1))
  random_model  <- data.frame(x = c(0, 1), y = c(0, 1))
  
  library(ggplot2)
  
  ggplot() +
    geom_line(aes(x, y, colour = "Modèle"), size = 1.1) +
    geom_path(
      data = random_model,
      aes(x, y, colour = "Modèle aléatoire"),
      linetype = 3,
      size = 1.1
    ) +
    geom_path(data = perfect_model,
              aes(x, y, colour = "Modéle théorique parfait"),
              size = 1.1) +
    geom_label(aes(
      x = 0.4,
      y = 0.6,
      label = paste0("AUC = ", round(auc, 3))
    )) +
    
    scale_x_continuous(breaks = seq(0, 1, 0.1)) +
    scale_y_continuous(breaks = seq(0, 1, 0.1)) +
    
    ggtitle("Courbe de Lift", subtitle = subtitle) +
    labs(x = perf@x.name, y = perf@y.name) +
    
    guides(col = guide_legend(title = NULL)) +
    
    theme(legend.justification = c(1, 0),
          legend.position = c(1, 0))
}
```


```{r}
xfname <- 'dtm_cross201512.csv' # raw data file for design matrix, ~ 1GB
if(file.exists('dtm_cross201512.desc')){
  datadesc <- dget('dtm_cross201512.desc')
  X <- attach.big.matrix(datadesc)
}else{
  X <- setupX(xfname, sep = ';',
            header = T,
            type = 'double') # create backing files (.bin, .desc)
}
  
y <- sub.big.matrix(X, firstRow = 10, lastRow = 100000, firstCol = ncol(X), lastCol = ncol(X))
X <- sub.big.matrix(X, firstRow = 10, lastRow = 100000, firstCol = 2, lastCol = ncol(X)-1)

```

Tentative biglasso
```{r}

library(doParallel)
cl<-makeCluster(spec = 2)
registerDoParallel(cl = cl)

time.fit <- system.time(
  fit <- biglasso(X, y, family = 'binomial', ncores = 3)
)

 stopCluster(cl)
```

Prédiction

```{r}
lambda <- fit$lambda[which.min(fit$loss)]
coef <- coef(fit, lambda=lambda, drop = TRUE)

proba <- predict(fit, X, type="response", lambda=lambda)

```

Estimation

```{r}
library(pROC)



```

